### ISSUE TITLE
Cannot find the module sgp4.earth_gravity

### ISSUE THREAD

**Issue by Tarlan0001** [brandon-rhodes/python-sgp4#24]
```
[root@docs orbital]# pip install sgp4
Requirement already satisfied: sgp4 in /usr/lib/python2.7/site-packages
[root@docs orbital]# python sgp4.py
Traceback (most recent call last):
  File "sgp4.py", line 4, in <module>
    from sgp4.earth_gravity import wgs84
  File "/usr/share/nginx/html/orbital/sgp4.py", line 4, in <module>
    from sgp4.earth_gravity import wgs84
ImportError: No module named earth_gravity
```

What could be the problem?

**Comment by brandon-rhodes** [comment]
You have given your own program the same name as the Python package `sgp4`. Try renaming your script so that it doesn't take away the name `sgp4` from the module.

**Comment by Tarlan0001** [comment]
Thanks, may be closed

**Comment by brandon-rhodes** [comment]
I'm glad that solved your problem! :)
