### ISSUE TITLE
days2hms can return seconds = 60.0

### ISSUE THREAD

**Issue by dmopalmer** [brandon-rhodes/python-sgp4#64]
In unaccelerated version, the `days2mdhms()` function can return a value with the previous minute and 60 seconds.  for example, day=133.35625 should give a time of `08:33:00` but instead gives `08:32:60`.  And the 60 is not 59.99999999 but a solid 60.  When used in a TLE, this causes TLE interpretation to break.

```
In [1]: from sgp4.api import accelerated, days2mdhms

In [2]: print(accelerated)
False

In [3]: print(days2mdhms(2020, 133.35625))
(5, 12, 8, 32, 60.0)

In [4]: _,_,_,_,s = days2mdhms(2020, 133.35625)

In [5]: print(s, s==60)
60.0 True
```

Therefore, in Skyfield

```
EarthSatellite('1 00000U 00000ZZ  20133.35625000  .00000000  00000-0  00000-0 0  9990',
                        '2 00000  24.6020  12.0680 3978520  69.4580 328.0792  0.99945723    08')
```
gives `ValueError: second must be in 0..59`:
```
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/sgp4/io.py", line 101, in twoline2rv
    def twoline2rv(longstr1, longstr2, whichconst, opsmode='i', satrec=None):
ValueError: second must be in 0..59
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3293, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-24-830190fd66c5>", line 1, in <module>
    EarthSatellite('1 00000U 00000ZZ  20133.35625000  .00000000  00000-0  00000-0 0  9990',
  File ".../lib/python3.8/site-packages/skyfield/sgp4lib.py", line 89, in __init__
    def __init__(self, line1, line2, name=None, ts=None):
  File ".../lib/python3.8/site-packages/sgp4/model.py", line 49, in twoline2rv
    @classmethod
  File ".../lib/python3.8/site-packages/sgp4/io.py", line 101, in twoline2rv
    def twoline2rv(longstr1, longstr2, whichconst, opsmode='i', satrec=None):
ValueError: second must be in 0..59

```

The error is where days2mdhms rounds off the seconds to 6 digits, which can round upwards from 59.99... .

**Comment by brandon-rhodes** [comment]
Drat. I'll go look right now!

**Comment by brandon-rhodes** [comment]
I have just pushed the release button for 2.11, which should fix the problem. Let me know if it looks like it solves your problem, and thanks for the quick report!

**Comment by dmopalmer** [comment]
That fixes things.  Thanks for the prompt fix.
